openapi: '3.0.3'
info:
  description: CSE186 Assignment 6
  version: 0.1.0
  title: CSE186 Assignment 6

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all Emails
      parameters:
        - name: mailbox
          in: query
          required: false
          schema:
            type: string
        - name: from
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Email Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mailbox'
        '404':
          description: Not Found
    post:
      description: Create a new email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmail'
      responses:
        '201':
          description: Email Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        '400':
          description: Bad Request
  /v0/mail/{id}:
    get:
      description: Get email by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        '404':
          description: Email Not Found
    put:
      description: Move email to a specified mailbox
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: mailbox
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Email Moved
        '404':
          description: Email Not Found
        '409':
          description: Cannot move to sent mailbox

components:
  schemas:
    Email:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          $ref: '#/components/schemas/Contact'
        from:
          $ref: '#/components/schemas/Contact'
        subject:
          type: string
        sent:
          type: string
          format: date-time
        received:
          type: string
          format: date-time
        content:
          type: string
    NewEmail:
      type: object
      properties:
        to:
          $ref: '#/components/schemas/Contact'
        subject:
          type: string
        content:
          type: string
      required:
        - to
        - subject
        - content
    Contact:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
    Mailbox:
      type: object
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            $ref: '#/components/schemas/Email'
